### PR TITLE
Adding methodology content

### PR DESCRIPTION
**Pull request by noahmanger**
Adds the content from https://github.com/18F/openFEC-web-app/issues/1275 to the "About this data" sections.

image

A couple design thoughts: There's a lot of content here. I know we never squared away the rules for what goes in these boxes, and have talked about having a separate methodology page. I think that that makes sense to do in the future, but this is fine for now. 

In the interim, we could either keep this as-is or set a max-height on these accordions with an inner scroll. What do you think @jenniferthibault ?

### CODE REVIEW

**Comment by jenniferthibault** [comment]
I added one commit for a few quick typo fixes that seemed to come from copying markdown >> html. 

Setting a max-height with an inner scroll makes sense to me until we can determine a pattern of what type of content goes in here. Before moving to a separate methodology page, can we add analytics trackers to these accordion buttons to see how many people click to open them?

**Comment by emileighoutlaw** [comment]
This looks really good. Thanks, y'all.

Would a Methodology page include everything under the current "Methodology" section? That makes sense to me.

**Comment by noahmanger** [comment]
Ok updated with the click tracking. The fixed height requires this though https://github.com/18F/fec-style/pull/408

**Comment by jenniferthibault** [comment]
Looks good, thank you!

**Pull request merged**
