### PR TITLE
Use Jinja blocks for flexible generic filters.

### PR DESCRIPTION
**Pull request by jmcarp**
This is an implementation of reusable filter sidebars, as @msecret proposed, that doesn't require all filter fields to be template includes. This approach uses blocks, which are more flexible and easier to customize.

This will cause merge conflicts with #336, so if we merge this branch, I can cherry-pick the SCSS changes there, or we can resubmit #336.

### CODE REVIEW

**Comment by msecret** [comment]
This is great. How do you propose we deal with the merge conflict? I could remove all template changes from #336 and then commit just the CSS changes? It *looks* like none of the changes I made in the templates were related to the styles.

**Comment by jmcarp** [comment]
Agreed, I think reverting the non-CSS changes in #336 would work. Or we could make a new PR that only includes the CSS changes--whatever's easier.

**Comment by msecret** [comment]
I make a new PR here:

https://github.com/18F/openFEC-web-app/pull/338

There were some template changes, unfortunately. I had to create a new wrapping div with a new class.

**Comment by msecret** [comment]
I have another fix to do on the filter panel but this looks good.

**Pull request merged**
