### PR TITLE
Feature/432 search

### PR DESCRIPTION
**Pull request by msecret**
Work in progress

Check commit message for more info

### CODE REVIEW

**Comment by noahmanger** [comment]
Looking good. Here's some things though (on a candidate search for obama):
- Remove the "View all" button and "Candidate results" header from the top. 
- The associated committees aren't right. They should be the Principal Campaign Committee for each. There's a bunch that aren't even authorized
- Let's remove the "most recent report" link 
- Replace the little arrows with `&raquo;`
- For Senate and Presidential races, either hide "District" or replace it with "Statewide" / "Nationwide"
- We can't sort by year, right? If not, can we at least sort to have Presidential candidates higher up?
- The "View all current candidates" link goes to "/committees"
- There's also some copy edits I know from the last round of feedback with FEC but I can make those before we merge.

**Comment by noahmanger** [comment]
Oh, and also the searchbar in the header needs the type dropdown.

**Comment by noahmanger** [comment]
Also, is there currently a limit on the search results? I'd like to try it with no limit.

**Comment by msecret** [comment]
@jmcarp can you look into Noah's comment "The associated committees aren't right. They should be the Principal Campaign Committee for each. There's a bunch that aren't even authorized"? I'm currently using the new search API route for the nested committee. Was that change not pushed to all envs?

**Comment by jmcarp** [comment]
@msecret checking that out now. Do you have an example of a committee that's wrong?

**Comment by noahmanger** [comment]
@msecret have you had a chance to fix the things I noted above? Doesn't look like it yet or maybe I'm just out of date.

**Comment by msecret** [comment]
- Hide header search bar on home page
- Change committee link to search
- No limit on api call
- Pass search term as q

**Comment by msecret** [comment]
What the to many results UI looks like, @noahmanger you'll probably want to make modifications

snapshot2

**Comment by noahmanger** [comment]
Perfect. Yeah I can work with that

On Wed, May 27, 2015 at 4:04 PM, Marco Segreto <notifications@github.com>
wrote:

> What the to many results UI looks like, @noahmanger
> <https://github.com/noahmanger> you'll probably want to make modifications
>
> [image: snapshot2]
> <https://cloud.githubusercontent.com/assets/1701077/7849414/05730c24-048a-11e5-93f5-d0d29d672e9f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/pull/165#issuecomment-106104740>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Pull request merged**
