### PR TITLE
Feature/fix receipts link

### PR DESCRIPTION
**Pull request by jmcarp**
Adds a few improvements related to https://github.com/18F/FEC/issues/72. It turned out that the receipts link on the committee detail page included a "cycle" parameter, which isn't one of the filters for the browse receipts page. This caused an immediate URL change upon loading the browse page.

* Fix link to receipts per cycle from the committee detail page
* Don't change URL based on irrelevant query parameters

cc @noahmanger

Note: looking at this code reminds me that it's kind of hairy in places and definitely in need of tests. I'm going to take a crack at refactoring the filter logic later this week--planning to add the missing tests there.

### CODE REVIEW

**Comment by noahmanger** [comment]
Only thing I noticed is the individual transaction links from the aggregates on election pages still have the `cycle` param.

**Comment by jmcarp** [comment]
Good catch @noahmanger. If I'm reading correctly, the URLs on the election page should be fixed in #876, so this patch should be good to go.

**Comment by jmcarp** [comment]
Patch updated @noahmanger.

**Comment by jmcarp** [comment]
Patch updated.

**Pull request merged**
