### PR TITLE
Fix Senate election URLs.

### LINKED ISSUE #914: Bug: Election links from Senator pages are broken
Election links from Senate candidate pages currently add district `00` to the URL, which takes you to broken senate pages.

As reported here: https://github.com/18F/FEC/issues/92

### PR DESCRIPTION
**Pull request by jmcarp**
* Remove "00" from Senate URLs
* Update unit tests

[Resolves #914]

cc @LindsayYoung, @noahmanger

### CODE REVIEW

**Comment by jmcarp** [comment]
Meant to target master, since this is a hotfix and should probably be deployed before the next release. As usual, if the patch is all right, either let me know so I can merge, or merge with `git flow hotfix finish...`.

**Comment by noahmanger** [comment]
LGTM but I don't understand the Python so @LindsayYoung should peek just to make sure.

**Comment by LindsayYoung** [comment]
LGTM

A thought going forward would be to have House Districts with 00 as "At large" since that would be the proper identification. I don't think that should hold up this patch.

As mentioned in #924, this will also fix 18F/FEC#92

**Comment by noahmanger** [comment]
Cool cool. @jmcarp do you want to merge this hotfix? Would be great to get it deployed to production today.

**Pull request merged**
