### PR TITLE
Use consistent limit for reports and totals charts.

### PR DESCRIPTION
**Pull request by jmcarp**
[Resolves https://github.com/18F/openFEC/issues/641]

@LindsayYoung I just saw that you marked this as not a problem, but it's a tiny change anyway. We can close the PR if it's better to wait for quarterly results.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
If you already started, you can go for it. We will need it eventually. 

When I said it was not a problem, I just meant it is not as important as the things that are broken or wrong.

Also what would need to scale the charts to work for a wide range of committees. Presidential are going to raise way more than a random committee. We want a scale to look good on both.

**Comment by noahmanger** [comment]
Yeah I think this is good to include now fwiw.

**Comment by noahmanger** [comment]
I'm running this locally and not seeing the results limited. 
screen shot 2015-04-29 at 11 31 33 am

**Comment by jmcarp** [comment]
@noahmanger what are you using for `FEC_WEB_API_URL`? I'm using https://api.open.fec.gov, and it seems to be working locally.

**Pull request merged**
