### PR TITLE
Fix New Relic configuration

### LINKED ISSUE #1701: restore new relic
it's not reporting

### PR DESCRIPTION
**Pull request by ccostino**
Closes #1701

This changeset fixes our New Relic configuration with the web app.  It is not currently reporting anything to New Relic (ping tests are working, though) and it is possible the settings were misconfigured.

To fix this, I mirrored the settings of the API configuration initially but that itself didn't work.  I then did the following:

* Updated the `newrelic` and `cfenv` packages to their latest versions
* Regenerated the `newrelic.ini` file with the updated `newrelic-admin` tool
* Modified the generated config file to match what we had previously (some settings had changed or been renamed)
* Moved the WSGI initialization code to after the New Relic initialization, just like in the API and CMS

A huge thank you to both @LindsayYoung and @tadhg-ohiggins for helping me out at various points with this!

/cc @LindsayYoung, @jontours, @tadhg-ohiggins

### CODE REVIEW

**Comment by ccostino** [comment]
Before merging this, we're going to do a manual deploy to `dev` and see if it works.

**Comment by LindsayYoung** [comment]
this has a please review on it, did you get it working?

**Comment by ccostino** [comment]
@LindsayYoung, no, I didn't and this fix didn't seem to take care of the issue.  I'm still unsure what the issue is at this point and will have to reach out to someone for additional help.  Perhaps there's a piece in the New Relic admin that needs to be configured too that I'm not aware of.

**Comment by ccostino** [comment]
Okay, this is working now!  We have data reporting in New Relic again for development (I had done a manual deploy to test).  Our `feature` environment doesn't seem to be working right at the moment, but once that's fixed it should report in there too, and once this goes up with the next staging and production deployments those should report again as well.

I am going to submit two additional PRs to update the New Relic dependencies and configs in the API and CMS as well to keep those up to date too.

**Comment by tadhg-ohiggins** [comment]
Great work persevering and tracking this down!

**Pull request merged**
