### PR TITLE
Pass correct full election flag.

### PR DESCRIPTION
**Pull request by jmcarp**
Goes with https://github.com/18F/openFEC/pull/1411

### CODE REVIEW

**Comment by noahmanger** [comment]
This works as expected, but I have a UI thought:

image

In the full-cycle view, I think we should specify the cycles for which each committee was active. So in this case, note which one was 2013-2014 and which was 2015-2016. Or at the least make clear which one is currently active. 

@jenniferthibault and @LindsayYoung do you have thoughts?

**Comment by noahmanger** [comment]
Also, sorry for not catching that earlier in the initial issue.

**Comment by jenniferthibault** [comment]
That makes sense to me, thanks for bringing it up! This is the first I've seen of a candidate that had two principal campaign committees, and I see how specifying when each is active would be helpful. 

An idea on format:

HILLARY CLINTON FOR PRESIDENT
yyyy–yyyy Principal campaign committe

**Comment by LindsayYoung** [comment]
Can we add some text that the finances are aggregated according to when the activity occurred and not what election the activity was for? I am afraid we are leading people astray. Committees can be paying off debts after the election and that doesn't help their current campaign.  

Having the date range for senate committees might occasionally be useful, I am not sure we need a lot of development around this edge case. But, if users want the date range, we should add it, perhaps that is something to test? There would be a tradeoff because there is already a lot of stuff on this page and more information would make it slightly busier.

**Comment by jmcarp** [comment]
What are our next steps here? Can we merge this patch, or should it wait until more interface changes? If the latter, who can we assign to design / implement changes?

**Comment by noahmanger** [comment]
I hear @LindsayYoung 's point about explaining that it's for the period there was activity and not the election, but I don't know that we need to worry about it. I think this communicates the main concept of "one of these is currently active, the other was active in the past":

image

@jenniferthibault I had to put the year range on a new line because it was causing the "principal campaign committee" to break onto a new line.

If this works, I have a patch that I can send a PR for.

**Comment by noahmanger** [comment]
Pending the :+1: here's the PR https://github.com/jmcarp/openFEC-web-app/pull/19

**Comment by emileighoutlaw** [comment]
This Q shouldn't hold a merge, but I'm wondering why we don't have the most recent principal campaign committee on top and cascade chronologically from there?

**Comment by noahmanger** [comment]
Nice catch. I just reversed it (using the jinja `reverse` filter, but let me know if there's a better way to do it).

**Comment by noahmanger** [comment]
Just realized that @jenniferthibault is out, so I think we can merge and adjust later if she has design feedback.

**Comment by jenniferthibault** [comment]
What Emileigh said is what I would have said :) Looks good, the new line is totally fine. Merging.

**Pull request merged**
