### PR TITLE
Show incumbent officeholders in election search.

### PR DESCRIPTION
**Pull request by jmcarp**
Depends on https://github.com/18F/openFEC/pull/1165.

### CODE REVIEW

**Comment by noahmanger** [comment]
Yes! Looks good to me.

**Comment by jmcarp** [comment]
Conflicts resolved. Ready for review @noahmanger @LindsayYoung.

**Comment by LindsayYoung** [comment]
I can take a look

**Comment by LindsayYoung** [comment]
Can we change the wording from "open seat" to "challenger"? That will make more sense in this context

**Comment by LindsayYoung** [comment]
Technically, we should say challenger if there is an incumbent and open seat if there is no incumbent, but calling them all challengers is less awkward that listing "open seat" when it is not.

**Comment by jmcarp** [comment]
@LindsayYoung sure, but that's not part of this patch, and it's a change on the API side--at the moment, we're displaying the candidate status values from FEC verbatim. This patch only touches the election search results:

**Comment by LindsayYoung** [comment]
Sorry to get sidetracked.

**Comment by jmcarp** [comment]
@LindsayYoung not at all--I think it's worth updating the wording. But in another patch :smiley:

**Pull request merged**
