### PR TITLE
Fix candidate links on election size aggregates.

### PR DESCRIPTION
**Pull request by jmcarp**
Thanks @patphongs for reporting!

[Resolves https://github.com/18F/FEC/issues/160]

### CODE REVIEW

**Comment by noahmanger** [comment]
This looks good, but what is it fixing?

**Comment by jmcarp** [comment]
See the original issue (https://github.com/18F/FEC/issues/160) for a description of the bug.

**Comment by jmcarp** [comment]
Also, since this is a hotfix, I can merge and deploy once it's ready.

**Comment by noahmanger** [comment]
Got it. Looks good to me.

**Pull request merged**
