### PR TITLE
Feature/coming soon

### PR DESCRIPTION
**Pull request by noahmanger**
Work in progress because I'm waiting on final copy, but this adds the "coming soon" section on the home page as well as tabs for filings on the candidate and committee pages, each with a coming soon message. 

screen shot 2015-05-30 at 8 43 46 pm
screen shot 2015-05-30 at 8 43 37 pm

### CODE REVIEW

**Comment by noahmanger** [comment]
There appears to be an issue with the page tabs. I'm trying to figure it out.

**Comment by noahmanger** [comment]
Ok, problem solved.

**Comment by LindsayYoung** [comment]
Do you think we should also mention the API in the done column and link to API documentation?

**Comment by noahmanger** [comment]
Status: Waiting on final clearance from FEC.

**Pull request merged**
