### PR TITLE
Feature/candidate other spending

### LINKED ISSUE #700: Implement "other spending" tab on candidate pages
In order for users to see which other groups are making IEs for or against a candidate, we should show them on the candidate's page.

Question for @jenniferthibault and @onezerojeremy : do you think this should just be on a separate tab? We had previously tried to remove tabs from candidate pages but this might be a fine reason to bring them back.

### PR DESCRIPTION
**Pull request by jmcarp**
Resolves #700. Flagging @noahmanger and @LindsayYoung to review behavior and code.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
I am so excited about this!

**Comment by noahmanger** [comment]
Nice! Working well. Can you add sorting to the third and fourth columns as well?

**Comment by LindsayYoung** [comment]
For the candidate page, can we show the candidate aggregates instead of the line items? So we would just show "$100 Fake PAC oppose" on the candidate page. What you have here, I think, would be perfect for the committee page.

Also @mahmanger @emileighoutlaw any ideas how to make it very clear that this money is not spent by the candidate?

**Comment by noahmanger** [comment]
Ah I was wondering about showing itemized vs. aggregates. I think I agree: let's show aggregates here and once we have an IE browse table, we can show the itemized there. 

And yes, we need a blurb explaining what IEs are and how they are not made in coordination with the candidate.

**Comment by LindsayYoung** [comment]
Now that I am thinking about it, I think that schedule_e should be in a browse view and committees should have the aggregates too, like the election pages.

**Comment by noahmanger** [comment]
schedule_e is IEs? We have an issue started for getting these on committee pages: https://github.com/18F/openFEC-web-app/issues/701

**Comment by LindsayYoung** [comment]
Yea, #701 says to aggregate by candidate and that sounds right to me.

**Comment by jmcarp** [comment]
Patch updated to use aggregates.

**Comment by noahmanger** [comment]
This looks good to me except "Given by" should be "Spent by". 

Are we heeding all these Hound warnings?

**Comment by jmcarp** [comment]
Updated. When I wrote the patch, we were still using "given by". I also changed the text on the election other spending tab.

For now, I'm paying attention to some Hound warnings more than others. I'm not fanatical about line length requirements, so am going to ignore those for now. We can customize the Hound configuration to skip certain warnings, which I'll get to soon.

**Comment by noahmanger** [comment]
Great. Makes sense to me. Hound does seem helpful for sure.

**Pull request merged**
