### PR TITLE
Feature/add filings dates

### PR DESCRIPTION
**Pull request by LindsayYoung**
the month, quarter, year checkbox and custom date box.

### CODE REVIEW

**Comment by noahmanger** [comment]
Working well, but they're different than what we said we wanted here: https://github.com/18F/openFEC-web-app/issues/530

Last quarter
This year
This cycle

Maybe for filings it makes sense to have "This quarter" as well? But I don't know if it makes sense for Receipts and Disbursements.

**Comment by LindsayYoung** [comment]
This makes the filters the same as the disbursement date filter.

**Comment by LindsayYoung** [comment]
This also gets rid of the stray "Today" on disbursements, so it would be good to merge

**Comment by noahmanger** [comment]
Just gotta sort out an errant diff in tables.js then should be good.

**Comment by noahmanger** [comment]
I think we still may want to add ones for "cycle" and "last quarter" separately though.

**Pull request merged**
