### PR TITLE
Feature/top-lists

### PR DESCRIPTION
**Pull request by noahmanger**
- [x] Top candidates
- [x] Top PACs
- [x] Top party committees

Top candidates:
image

### CODE REVIEW

**Comment by noahmanger** [comment]
Ok @jontours I added the code for top PACs and party committees. The test data only has one of each for 2016, but it seems to be working. Thanks for helping me get the API branch going!

**Comment by jontours** [comment]
@noahmanger I did push another subset that has more than one party committee, if you want to see more interesting results.  It was tough writing this feature as the fec_vsum_f3x table was pretty sparse in the subset data.  

Also added a commitee_type filter to the api.  So for example, if you do a get on the 'party' endpoint and pass a parameter, "type=X', you will get back only X-type party committees, don't know if that will be needed, but may be nice to have for other unforeseen features

**Comment by adborden** [comment]
:+1:

**Comment by jontours** [comment]
This looks good for me except for candidates, I'd say it's ready to merge as the broken candidates is probably on the api.  Also, the formatting is wacky for me but could be my local set-up.

**Comment by noahmanger** [comment]
Cool. I just pushed one more commit to fix a styling issue. But if that looks good then we can merge this. I'll make a separate PR into the release branch.

**Comment by jontours** [comment]
This can be closed without merging, was referenced by newer pull request, which has been already merged.

**Comment by jontours** [comment]
Ah wait, crap, this was for develop.  The feature branch should be merged back into develop as part of the deployment correct?  @adborden @ccostino

**Comment by adborden** [comment]
Ah, yep good point @jontours. Yeah, I double checked that this branch made it into the release branch. We can merge this now, otherwise it will be merged back into develop later today when we finish the release and merge the branches. I don't think it matters either way. One less merge commit in the history if we wait :)

**Pull request merged**
