### PR TITLE
Adding a statutory candidate check box

### PR DESCRIPTION
**Pull request by LindsayYoung**
The statutory candidate data is much cleaner, so it makes a good default.

We can just add 'candidate_status=C' to all the links to that page. Is there a better way to handle that default?

I am simplifying this a bit, the full list of codes codes is:

C = Statutory candidate
F = Statutory candidate for future election
N = Not yet a statutory candidate
P = Statutory candidate in prior cycle

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Fixes #785

**Comment by LindsayYoung** [comment]
Just C, might be too limiting, we might want to include all non-nulls, what do you think @PaulClark2

**Comment by PaulClark2** [comment]
If the default is "statutory candidate" we probably want to use "C," "F" and "P" as all of these codes indicate the candidate has spent or raised $5000.   The default value for candidate status (cand_status) is "N."  We may need to try including and excluding codes to determine what works best.

**Comment by jmcarp** [comment]
What's the status of this patch @LindsayYoung? Do we want to stick with "C" only or add more options? Regardless of which statuses we choose by default, it seems like we'd want to allow users to filter by any status.

**Comment by LindsayYoung** [comment]
Sorry, did not see this comment before, I will take a look!

**Comment by LindsayYoung** [comment]
We were talking about defaulting to the statutory candidates for the browse views, so I am going to change the link slightly, I think we should change the language on the following to reflect the new, curated view, Instead of "All 2016 presidential candidates", just " 2016 presidential candidates" and so on. 

Would that be OK @emileighoutlaw and @noahmanger ?

screen shot 2015-10-08 at 11 10 53 am

**Comment by emileighoutlaw** [comment]
I think that sounds great to me!

**Comment by emileighoutlaw** [comment]
Great thought

**Comment by LindsayYoung** [comment]
Going to change links in the fec-style dropdown next

**Comment by noahmanger** [comment]
Great!

On Thu, Oct 8, 2015 at 9:55 AM, Lindsay Young <notifications@github.com>
wrote:

> Going to change links in the fec-style dropdown next
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/pull/795#issuecomment-146621344>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
The API part of this is working locally and on production, but is having issues on dev, I will look into that now.

(After this, merge 18F/fec-cms#89)

**Comment by noahmanger** [comment]
Where's this at?

**Comment by LindsayYoung** [comment]
I think the only thing left is debugging the tests.

**Comment by LindsayYoung** [comment]
It looks like the tests are comparing results against the API, so we need to filter those results the same, I am not finding where it is making the comparison call in the test to add the same filtering.

**Pull request merged**
