### PR TITLE
Canonical AO page

### PR DESCRIPTION
**Pull request by adborden**
Depends on https://github.com/18F/fec-style/pull/465

### CODE REVIEW

**Comment by adborden** [comment]
screenshot from 2016-08-10 13-40-26

**Comment by adborden** [comment]
@jenniferthibault can you look this over as well?

**Comment by jenniferthibault** [comment]
yup! I'll look tomorrow

**Comment by adborden** [comment]
Paired with @jenniferthibault and we updated the heading styles in https://github.com/18F/fec-style/pull/465

## Main header

screenshot from 2016-08-11 18-20-34

## Election lookup
We chose to consolidate one similar case on the election lookup page.

**Before**
screenshot from 2016-08-11 18-15-20

**After**
screenshot from 2016-08-11 17-24-34


## Data tables

No visual change to the data tables, but we changed the behavior by adding a subclass. Since by default, data tables don't have a top border, it's awkward for them to have cell borders in the header row. So we moved the borders into a subclass `.data-table--heading-borders` and added them to all the places that expect borders in the header row.

**Comment by adborden** [comment]
cc @noahmanger

**Comment by noahmanger** [comment]
👍 from me! I'll @jenniferthibault look over again, but I'm good to merge in once that's good.

**Comment by jenniferthibault** [comment]
Hi! So sorry for not checking in on this before signing off, but on trying to clear out my notifications I noticed one tiny thing in this: that `document` icon we spent all that time adding in https://github.com/18F/fec-style/pull/462 isn't showing up:

screen shot 2016-08-12 at 10 08 04 pm

Not launch critical, but I didn't want to lose track of it permanently.

**Pull request merged**
