### PR TITLE
Re-ordering reports and forms

### PR DESCRIPTION
**Pull request by noahmanger**
Re-orders the report dropdowns to the order described in #360 

Update:
- Breaks report types out into separate filters per the discussion in #360 
- Instead of showing all the new filters on the filings tab on the committee page, this removes those filters altogether, further differentiating this tab from the main filings browse page (something we learned may be helpful from user testing)

screen shot 2015-09-10 at 10 49 54 am

screen shot 2015-09-10 at 10 53 02 am

### CODE REVIEW

**Comment by jmcarp** [comment]
These codes don't match the order or content of #360:
* The 10* codes should be in the "Election Sensitive Reports" section
* The MSA and MSY codes have the wrong text (both of those codes also have the same text in our version, which is confusing)
* We're using abbreviations instead of full terms for codes like ADJ (we say "COMP ADJUST AMEND"; #360 says "Comprehensive Adjusted Amendment").

I also see that code 60D is described as post-election in #360 but post-convention here (and in http://www.fec.gov/finance/disclosure/metadata/ReportTypeCodes.shtml). @PaulClark2, can you clarify the description of code 60D?

I think we should use the text and order from #360 verbatim here. Thoughts @noahmanger @LindsayYoung?

**Comment by PaulClark2** [comment]
Agreed we should use #360 and we should avoid abbreviations if possible. 

"60D' should be Post-Convention

For the bundling reports:  

"MSA"	Monthly Semi-Annual (MY)
"MSY"	Monthly Semi-Annual (YE)

We could use the following descriptions if they are clearer.  We could also drop the parenthetical

"MSA"	Monthly Semi-Annual Mid-Year (MY)
"MSY"	Monthly Semi-Annual Year-End (YE)

**Comment by noahmanger** [comment]
Ah, thanks for catching @jmcarp . I wasn't sure if we chose the other labels for a reason. I've updated to more closely reflect that list, but have a few more questions in #360 .

**Comment by noahmanger** [comment]
Updated the main note above with recent changes. I'm pretty sure I have the list captured correctly with the right order and labels, but would appreciate a second set of eyes to make sure I got it right.

**Comment by jmcarp** [comment]
LGTM

**Pull request merged**
