### PR TITLE
Feature/staging banner

### PR DESCRIPTION
**Pull request by noahmanger**
Adds the "Staging" / "Development" banners to the site, depending on the environment you're on.

Resolves https://github.com/18F/openFEC/issues/1216

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@noahmanger Just noticed that on the homepage it says "Development" but on other pages, it says "Develop" — is that a web-app vs CMS thing?

**Comment by noahmanger** [comment]
Oops. Yeah, I just accidentally wrote it two ways in the different apps. What do we want to call them?

**Comment by jenniferthibault** [comment]
Probably "Development" looking at @emileighoutlaw 's comment here: https://github.com/18F/openFEC/issues/1216#issuecomment-148492719

**Comment by noahmanger** [comment]
Got it.

On Fri, Oct 16, 2015 at 10:11 AM, Jennifer Thibault <
notifications@github.com> wrote:

> Probably "Development" looking at @emileighoutlaw
> <https://github.com/emileighoutlaw> 's comment here: 18F/openFEC#1216
> (comment)
> <https://github.com/18F/openFEC/issues/1216#issuecomment-148492719>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/pull/844#issuecomment-148775287>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
Yep! I like Development. :)

**Pull request merged**
