### PR TITLE
Fixed more info links on advanced data committees tab

### PR DESCRIPTION
**Pull request by johnnyporkchops**
Links were pointing to old reg/rptng page, so they point to help4cc page anchors

### CODE REVIEW

**Comment by noahmanger** [comment]
Does this need to be a hotfix, or can we just merge into develop?

Also, please include `hotfix` in the title of hotfix PRs so they don't accidentally get merged in with Github.

**Comment by johnnyporkchops** [comment]
It does not have to be a hot fix if you do not think its urgent

**Comment by noahmanger** [comment]
I can go either way. It's simple enough. @LindsayYoung ?

**Comment by johnnyporkchops** [comment]
My understanding of hofixes is that they are for things that are either urgent or so simple that they don't require a alot of development or review, but  could have that wrong. If there is a release coming up then I am sure its fine for whatever works for better for the reviewer/merger. This is just some dead links that Wie pointed out in slack this week.

**Comment by noahmanger** [comment]
I caught one more of these that needed to be replaced (on the candidates tab) and also I could only get the anchor tags to work if there was no `/` before the URL fragment, so I removed those. 

Can someone double-check though?

**Comment by noahmanger** [comment]
@patphongs can you take a look at this and verify the links are right? I had to push a couple commits.

**Comment by noahmanger** [comment]
Changed this to target develop and we'll just include it in the release.

**Comment by patphongs** [comment]
Thanks! I didn't get to this today but will review tomorrow.

**Pull request merged**
