### PR TITLE
Getting panel to work on modal

### PR DESCRIPTION
**Pull request by msecret**
- Rename the UI of the pop-out from "modal" to "panel". This was renamed
because this UI will not be strictly a modal. It will act as a modal
on mobile and as a split 50% panel on tablet, up. @noahmanger, please
let me know if theres a better name.
- Change the columns around to have an arrow column at the end of the
rows.
- Make the whole row clickable to open the panel, if you click on a link
it will pass through and open the link.

This needs some of the work done in #337, #338 in order to get
expeditures working.

### CODE REVIEW

**Comment by noahmanger** [comment]
So this isn't currently styled to show the split view, right?

Also, you're right on the tablet-up layout, but on mobile it should actually be more like a two panel view, but where you go between them, rather than a pop up. Like this: https://github.com/18F/openFEC-web-app/issues/317

I can explain better in person.

Do you want to merge this in now?

**Comment by msecret** [comment]
@noahmanger correct, this does not implement the split view right now. I'm attempting to break the work into small chunks, and all this does is rename the modal, create the table cell for the arrow in the UI, and ensure the whole row is clickable to open the modal on mobile and full screen.

**Comment by noahmanger** [comment]
+1

On Tue, Jul 21, 2015 at 8:13 AM, Marco Segreto <notifications@github.com>
wrote:

> @noahmanger <https://github.com/noahmanger> correct, this does not
> implement the split view right now. I'm attempting to break the work into
> small chunks, and all this does is rename the modal, create the table cell
> for the arrow in the UI, and ensure the whole row is clickable to open the
> modal on mobile and full screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/pull/342#issuecomment-123365707>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Looks fine to me except there's a conflict in tables.js.

**Pull request merged**
