### PR TITLE
Feature/styleguide adjustments

### PR DESCRIPTION
**Pull request by noahmanger**
Small class name adjustments to go with cleanup done in https://github.com/18F/fec-style/pull/287

Fixes https://github.com/18F/fec-style/issues/299

### CODE REVIEW

**Comment by jenniferthibault** [comment]
A few things: 

Not seeing the styles come through on the candidate profile pages:

screen shot 2016-04-08 at 6 26 23 pm

Annd should switch to regular style here for 404 errors:

screen shot 2016-04-08 at 6 27 25 pm

Also not seeing the style come through for the feedback button
screen shot 2016-04-08 at 6 29 02 pm

**Comment by jenniferthibault** [comment]
Whoops, found one more (that was harder to find!)
I seem to have lost the download buttons, which should be cta-alt like the calendar:

screen shot 2016-04-08 at 6 55 39 pm

**Comment by noahmanger** [comment]
Got it! The matter of the styles not coming through in those places is likely due to needing to run `npm run build`.

**Comment by noahmanger** [comment]
Here's how download buttons look for me. Is this right? 
image

**Comment by jenniferthibault** [comment]
I was originally thinking outlined (`alt` style) but I think you're right. Full CTA style because this is the thing everyone wants 👍

**Pull request merged**
