### PR TITLE
Feature/gov cloud support

### LINKED ISSUE #1684: Move openfec-web-app to new cloud.gov
We need to move the openfec-web-app to the new cloud.gov, which requires:

- [ ] Use built-in routing feature instead of the proxy app
- [x] Make sure new relic is going
- [ ] Make sure github is reachable by the app for feedback
- [x] Make sure deployment works with the invoke task
- [ ] Make sure deployment works by travis
- [x]  Move dev/staging/prod to cloud.gov url instead of 18F.gov

(updated issue since ethnio is off)

### PR DESCRIPTION
**Pull request by ccostino**
Closes #1684

**WIP:  PLEASE DO NOT MERGE**

This changeset includes the necessary changes required to migrate the FEC web app to the GovCloud cloud.gov environment from the old East/West environment. Some of these changes may end up being unwound later on, but for the time being these are the pieces that are required in order to get the app running in the new environment.

**TODO**

- [ ] Update and fix `invoke` and the tasks we have
- [x] Ensure CF autopilot plugin is working correctly with deployment

### CODE REVIEW

**Comment by ccostino** [comment]
@LindsayYoung, I know you had done this work initially but I had to update the app in GovCloud.  If there's anything I'm missing here please let me know!

**Comment by LindsayYoung** [comment]
- review and merge
- make a new WIP pr for this branch

**Comment by LindsayYoung** [comment]
check deploys in the tasks.py

**Comment by vrajmohan** [comment]
We should fix FEC_WEB_API_URL on Line 68 of README.md.

**Pull request merged**
