### PR TITLE
Landing chart connection to api

### PR DESCRIPTION
**Pull request by xtine**
Updates the Raising and Spending data landing charts to use data from the API. #1603 

Requires 18F/fec-style#552

### CODE REVIEW

**Comment by xtine** [comment]
@noahmanger: I'll need your help to cycle to previous 2 year periods.

**Comment by noahmanger** [comment]
@xtine re: cycling to previous period, let's not worry about that for now. Let's just get this in and then add that on.

**Comment by xtine** [comment]
With 18F/openFEC#1990, live datasets look more accurate:

screen shot 2016-10-20 at 3 01 42 pm
screen shot 2016-10-20 at 3 36 34 pm

While growth lines pattern looks good, the numbers are a bit off from the hardcoded values (beta.fec.gov/data). @LindsayYoung can you double check if there is a discrepancy from either side?

**Comment by noahmanger** [comment]
The data seems to be very off, but I believe this is an API issue as I'm looking at the results there. 

For instance, by Aug 31, 2016, the data Paul gave us says $1.7b for candidate spending, and the API is showing ~$3.3b. 

But this looks good, so I'll merge and open a new issue for validating data.

**Pull request merged**
