### PR TITLE
Feature/update election lookup

### LINKED ISSUE #592: Finish remaining features on election lookup
A few remaining features to add to the election lookup page:
- [x] Add URL updating on searches
- [x] Show the full list of candidates in a state upon selecting a state
- [x] Make districts on the map have a stroke width of 1px
- [x] Show a message when more than on district match a zipcode

And a thought: should the election map first just display state outlines? And then if you select a state it zooms in and shows the districts? Would definitely make the map less cluttered.

[Full mockup here](https://invis.io/9N43H4YBJ)

### PR DESCRIPTION
**Pull request by jmcarp**
* Add persistent URLs for election searches
* Show results for states without district selection
* Show warning on multiple districts per zip code

Note: the last item from #592 is addressed in 18F/fec-style/pull/69.

[Resolves #592]

### CODE REVIEW

**Comment by jmcarp** [comment]
@noahmanger: the warning for zip codes with multiple districts is basically unstyled--can you take a look? To test, try 60442 (four districts!) or 19041 (two).

**Comment by noahmanger** [comment]
This is working great. The only regression I caught is that the list of districts no longer updates based on the districts in that state.

**Comment by jmcarp** [comment]
Should be fixed now @noahmanger. I also added the left half of #591 for review.

**Comment by noahmanger** [comment]
Beautiful. I'll style the component on the home page separately.

**Pull request merged**
