### PR TITLE
Update frontend dependencies.

### PR DESCRIPTION
**Pull request by jmcarp**
Update DataTables and DataTables-Responsive. DataTables has moved all of
their libraries to npm, which means we no longer need to install
extensions from third parties (no more drmonty-datatables-responsive).
Once https://github.com/DataTables/Responsive/issues/61 is resolved, we
should be able to upgrade to the next major version of
DataTables-Responsive.

This patch also grabs some recent bug fixes from the Leaflet team.

### CODE REVIEW

**Comment by noahmanger** [comment]
I was meaning to ask: do we even need DataTables-Responsive anymore? Is that what controls the column hiding? Or is that native the main library?

**Comment by jmcarp** [comment]
Yep, the responsive extension updates column visibility on resize. I turned it off to see what would happen--the tables didn't look terrible, but too many columns were displayed at some window sizes:

screen shot 2015-11-17 at 1 59 04 pm

**Comment by noahmanger** [comment]
Great. Just checking.

On Tue, Nov 17, 2015 at 11:02 AM, Joshua Carp <notifications@github.com>
wrote:

> Yep, the responsive extension updates column visibility on resize. I
> turned it off to see what would happen--the tables didn't look terrible,
> but too many columns were displayed at some window sizes:
>
> [image: screen shot 2015-11-17 at 1 59 04 pm]
> <https://cloud.githubusercontent.com/assets/1633460/11221552/ba32992c-8d33-11e5-94c7-f66cd44fdb39.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/pull/955#issuecomment-157471522>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
This should be good to go @noahmanger!

**Pull request merged**
