### PR TITLE
Feature/update maps

### PR DESCRIPTION
**Pull request by jmcarp**
* Build US state topojson from Census data (fixes FIPS code for Minnesota)
* Use the same FIPS data as the API for developer sanity
* Fix a few miscellaneous election map bugs
* Add data provenance notes

### CODE REVIEW

**Comment by noahmanger** [comment]
Which election map bugs does this fix? Just so I know where to look.

**Comment by jmcarp** [comment]
Good call--I've been meaning to institute some standards for documenting issues and pull requests, and the description of this patch wouldn't have made the cut.

Fixes:
* Clicking on Minnesota doesn't zoom in on Nevada
* Clicking on Alaska doesn't highlight all states (this was happening because Alaska so big that zooming to it triggers the map to show all states)
* If the URL includes a zip / state / district, don't draw the national map and then switch to the zip / state / district map

**Comment by noahmanger** [comment]
Great. Functionally works great. @msecret do you want to review the js?

**Comment by jmcarp** [comment]
@msecret do you have time to review? Would like to get this squared away soon if possible.

**Comment by jmcarp** [comment]
@noahmanger turns out Marco's OOO for the week. We may want to merge now and ask for a review next week.

**Pull request merged**
