### PR TITLE
Adding data for form 5s and 24/48 hour notices to IEs

### PR DESCRIPTION
**Pull request by noahmanger**
- This removes the previous filter that only showed `F3X` figures, so `F5` data is now included.
- It adds a toggle filter for "Summary reports" vs "24 and 48 hour notices" (language needs to be changed, I'm sure). This filter defaults to show _only_ `F3X` and `F5` ("Summary reports") but can be toggled to show _only_ data from notices. 
- Aggregate links (e.g. from a total on a candidate page) default to only the "summary report" data

image

**Remaining work:**
- [x] @jwchumley verify the data is showing as expected
- [x] @LindsayYoung verify the data is showing as expected
- [x] Finalize language for the toggle (cc @emileighoutlaw )
- [x] Add a tooltip to the toggle if necessary (cc @emileighoutlaw )
- [x] Update the `ToggleFilter` component to output the correct text in the tag

Original issue discussion over here: https://github.com/18F/openFEC-web-app/issues/1436

Requires https://github.com/18F/fec-style/pull/530 for the tags

### CODE REVIEW

**Comment by jontours** [comment]
@noahmanger in the interest of time and sanity I think I may move the 24/48 hour notices into a seperate endpoint.  Something like `/sched_e/notice` and then you can filter that endpoint down more based form type, i.e 'f3x', 'f5' etc.  Let me know if that is not workable.

**Comment by noahmanger** [comment]
Oh yeah, that would totally work. We can just use the same front-end logic that we use for toggling between efilings and processed data.

**Comment by noahmanger** [comment]
@jontours I just updated this so that the toggle toggles between `/schedules/schedule_e/` and `/schedules/schedule_e/notice` . But my local server is showing what looks to be some SQL errors. 

The big thing that I want to test and maybe you can just tell me: will the two endpoints have all the same filters? Will their responses be the same? Wondering if we'll need to account for that at all here.

**Comment by jontours** [comment]
@noahmanger I did checkout this PR yesterday, I can pull the latest updates and see what's up.

**Comment by noahmanger** [comment]
I just added a new `filing_form_type` filter that is enabled for "Summary reports" but disabled for notices:

image

image

**Comment by noahmanger** [comment]
Ok @jontours I reverted this so it just uses a single endpoint. It uses the `is_notice` flag. Not sure if that's still the param though.

**Comment by jontours** [comment]
Thanks @noahmanger, yes that is still the parameter used.

**Comment by noahmanger** [comment]
Ok! This is all ready for review. I tested against the API branch and it's working as expected.

**Review by jontours — APPROVED** [review]
This looks good to go.  I noticed the descriptions were blank for notices, but after investigating through the API they some descriptions are null in the database.  I'll merge if it's ready to go.

**Comment by noahmanger** [comment]
Let's do it. Thanks!

**Pull request merged**
