### PR TITLE
Adding beginning image number filter to filings

### PR DESCRIPTION
**Pull request by noahmanger**
image

In response to https://github.com/18F/openFEC-web-app/issues/1892

### CODE REVIEW

**Comment by LindsayYoung** [comment]
The file numbers and image numbers have different meanings, which is this filtering on?

**Comment by noahmanger** [comment]
Oops, I meant to say "image number". It's `beginning_image_number`. Good catch!

**Comment by noahmanger** [comment]
image

**Comment by noahmanger** [comment]
As discussed in grooming, we want to use this approach for now. Can someone review and merge?

**Comment by LindsayYoung** [comment]
This works. Thanks!

**Pull request merged**
